openapi: 3.0.4
info:
  title: LB Labs
  version: 1.0.0
paths: {}
components:
  schemas:
    MyObject:
      type: object
      properties:
        MyProp:
          type: string
          example: 'abc'
